-- This Source Code Form is subject to the terms of the bCDDL, v. 1.1.
-- If a copy of the bCDDL was not distributed with this
-- file, You can obtain one at http://beamng.com/bCDDL-1.1.txt

return {
    hide_ui           = { replacement = "toggleUi" },
    steer             = { replacement = "steering" },
    steer_direct      = { replacement = "steering" },
    accelerate_direct = { replacement = "accelerate" },
    brake_direct      = { replacement = "brake" },
    clutch_direct     = { replacement = "clutch" },
    handle_escape     = { replacement = "toggleMenues" },
    gamepadPitch      = { replacement = "rotate_camera_vertical" },
    gamepadYaw        = { replacement = "rotate_camera_horizontal" },
    joystickPitch     = { replacement = "rotate_camera_vertical" },
    joystickYaw       = { replacement = "rotate_camera_horizontal" },
    switch_reset_vehicle   = { replacement = "switch_next_vehicle" },
    increase_gamepad_zoom2 = { replacement = "increase_zoom" },
    decrease_gamepad_zoom2 = { replacement = "decrease_zoom" },
    setZoomFOV        = { obsolete = true },
    toggleZoom        = { obsolete = true },
    toggleQuickAccess = { replacement = "toggleMenues" },
    toggle_dashboard  = { replacement = "toggleMenues" },
    reload_bindings   = { obsolete = true },
    show_metrics      = { replacement = "cycle_metrics_back" },
    toggleFPS         = { replacement = "cycle_metrics_fwd" },
    toggleFreeLook    = { obsolete = true },
    increase_gamepad_zoom = { replacement = "increase_zoom" },
    decrease_gamepad_zoom = { replacement = "decrease_zoom" },
    toggle_physics    = { replacement = "pause" },
    switch_camera     = { replacement = "switch_camera_next" },
    camera_hotkey_1   = { replacement = "camera_1" },
    camera_hotkey_2   = { replacement = "camera_2" },
    camera_hotkey_3   = { replacement = "camera_3" },
    camera_hotkey_4   = { replacement = "camera_4" },
    camera_hotkey_5   = { replacement = "camera_5" },
    camera_hotkey_6   = { replacement = "camera_6" },
    camera_hotkey_7   = { replacement = "camera_7" },
    camera_hotkey_8   = { replacement = "camera_8" },
    camera_hotkey_9   = { replacement = "camera_9" },
    camera_hotkey_0   = { replacement = "camera_10" },
    camera_hotkey_1_mod1 = { obsolete = true },
    camera_hotkey_2_mod1 = { obsolete = true },
    camera_hotkey_3_mod1 = { obsolete = true },
    camera_hotkey_4_mod1 = { obsolete = true },
    camera_hotkey_5_mod1 = { obsolete = true },
    camera_hotkey_6_mod1 = { obsolete = true },
    camera_hotkey_7_mod1 = { obsolete = true },
    camera_hotkey_8_mod1 = { obsolete = true },
    camera_hotkey_9_mod1 = { obsolete = true },
    camera_hotkey_0_mod1 = { obsolete = true },
    reload_system_lua = { obsolete = true },
    grabNodeToggle   = { replacement = "nodegrabberRender" },
    grabNodeLock   = { replacement = "nodegrabberGrab" },
    grabNodeForce   = { replacement = "nodegrabberStrength" },
    grabNodeModeToggle   = { replacement = "nodegrabberAction" },
    slow_motion       = { replacement = "toggle_slow_motion" },
    realtime_motion   = { replacement = "toggle_slow_motion" },
    oldEditorToggle   = { replacement = "editorToggle" },
    toggleRadialMenu  = { obsolete = true },
    delete_ai_node   = { replacement = "editorDeleteSelection" },
    delete_road_node   = { replacement = "editorDeleteSelection" },
    delete_river_node   = { replacement = "editorDeleteSelection" },
    delete_meshRoad_node   = { replacement = "editorDeleteSelection" },
    delete_decal   = { replacement = "editorDeleteSelection" },
    select_all_road_nodes   = { replacement = "editorSelectAll" },
    select_all_river_nodes   = { replacement = "editorSelectAll" },
    select_all_meshRoad_nodes   = { replacement = "editorSelectAll" },
    cycle_metrics_fwd = { replacement = "cycle_metrics" },
    cycle_metrics_back = { replacement = "cycle_metrics" },
    toggleConsole = { replacement = "toggleConsoleNG" },
    clear_console = { obsolete = true },
    annotatedScreenShot = { obsolete = true},
    key_q               = { obsolete = true},
    key_e               = { obsolete = true},
    key_w               = { obsolete = true},
    key_s               = { obsolete = true},
    key_a               = { obsolete = true},
    key_d               = { obsolete = true},
    key_t               = { obsolete = true},
    key_f               = { obsolete = true},
    key_g               = { obsolete = true},
    key_h               = { obsolete = true},
    key_r               = { obsolete = true},
    key_y               = { obsolete = true},
}
